### ISSUE TITLE
Create a pill detail page

### ISSUE THREAD

**Issue by raemarchetti** [raemarchetti/magic-pills-marketplace#6]
User Story: As a visitor/user, I want to see detailed descriptions and information about each magic pill, including its effects, ingredients, and possible side effects, to make an informed decision before purchasing.

Technical Specifications: 
1. Define a route and corresponding controller action to fetch the details of a specific product from the database.
2. Design and implement a view template to display the detailed information of the selected pill.
3. Display comprehensive information about a selected magic pill

**Comment by marimilani** [comment]
falta view e add imagem

**Comment by raemarchetti** [comment]
view added, image missing
